In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    "/Users/alexandralugova/Documents/GitHub/MH-old-workers/data/datasets/data_clean_w456.csv"
)
indexes = pd.read_csv(
    "/Users/alexandralugova/Documents/GitHub/MH-old-workers/data/datasets/work_quality_indexes.csv"
)

In [3]:
df = df.merge(indexes, on=["country", "year", "isco"], how="inner")

In [4]:
df

,mergeid,wave,year,age,nb_children,partnerinhh,job_status,eurod,eurodcat,country,...,retirement_age,work_horizon,work_horizon_change,jqi_monthly_earnings,jqi_skills_discretion,jqi_social_environment,jqi_physical_environment,jqi_intensity,jqi_prospects,jqi_working_time_quality
0,AT-011070-01,4,2011,59.0,2.0,1,Civil servant,2.0,0,Austria,...,60.0,1.0,0.0,1775.298469,76.869369,75.804924,91.904085,33.086420,31.155303,85.271991
1,AT-326780-02,4,2011,57.0,2.0,1,Civil servant,5.0,1,Austria,...,60.0,3.0,0.0,1775.298469,76.869369,75.804924,91.904085,33.086420,31.155303,85.271991
2,AT-413796-01,4,2011,55.0,1.0,1,Civil servant,2.0,0,Austria,...,60.0,5.0,0.0,1775.298469,76.869369,75.804924,91.904085,33.086420,31.155303,85.271991
3,AT-433002-01,4,2011,55.0,1.0,0,Civil servant,6.0,1,Austria,...,60.0,5.0,0.0,1775.298469,76.869369,75.804924,91.904085,33.086420,31.155303,85.271991
4,AT-594803-02,4,2011,57.0,1.0,1,Civil servant,4.0,1,Austria,...,60.0,3.0,0.0,1775.298469,76.869369,75.804924,91.904085,33.086420,31.155303,85.271991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8083,SI-891208-01,6,2015,60.0,1.0,1,Public sector employee,3.0,0,Slovenia,...,65.0,5.0,0.0,3094.944580,81.905090,84.090909,98.076923,20.000000,12.500000,94.531250
8084,SI-945439-01,6,2015,60.0,0.0,1,Private sector employee,0.0,0,Slovenia,...,65.0,5.0,0.0,1602.959351,85.180511,86.363636,67.948715,56.666668,0.000000,37.500000
8085,SI-951611-02,6,2015,54.0,2.0,1,Public sector employee,3.0,0,Slovenia,...,60.0,6.0,0.0,1078.914917,60.034649,50.000000,80.769230,38.888890,31.250000,96.875000
8086,SI-966058-01,6,2015,57.0,2.0,0,Public sector employee,4.0,1,Slovenia,...,60.0,3.0,0.0,816.507407,59.617775,81.118881,85.520363,27.450981,42.857143,89.389706
8087,SI-974683-01,6,2015,57.0,2.0,1,Public sector employee,1.0,0,Slovenia,...,60.0,3.0,0.0,828.986061,38.752253,85.714286,81.891027,67.430555,58.653846,91.523438

In [5]:
df.mergeid.nunique()

4710

In [6]:
df.groupby("country").mergeid.nunique()

country
Austria           260
Belgium           677
Czech Republic    347
Denmark           382
Estonia           518
France            323
Germany           620
Italy             455
Slovenia          294
Spain             579
Switzerland       255
Name: mergeid, dtype: int64

In [7]:
df.groupby("year").mergeid.nunique()

year
2011    1954
2013    2760
2015    3374
Name: mergeid, dtype: int64

In [9]:
df.to_csv(
    "/Users/alexandralugova/Documents/GitHub/MH-old-workers/data/datasets/final_w456.csv",
    index=False,
)